import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import { Inter } from "next/font/google"
import "./globals.css"
import { siteConfig } from "./siteConfig"
import { Sidebar } from "@/components/ui/tremor/ui/navigation/Sidebar"

import dynamic from 'next/dynamic'


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Payven",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-tremor-background text-tremor-content-emphasis`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="flex min-h-screen">
              <Sidebar />
              <div className="flex-1 overflow-x-hidden">
                <main className="lg:pl-72">{children}</main>
              </div>
            </div>
        </ThemeProvider>
      </body>
    </html>
  )
}